### ISSUE TITLE
we need a feature tracking system

### ISSUE THREAD

**Issue by caogecym** [valleyrain-org/www-old#6]
I propose this one: https://trello.com/b/xBtTMnQ8/-

We can propose, discuss, and track progress of each feature

**Comment by tao-guo** [comment]
已经有了: https://trello.com/b/4RTmf30J/roadmap

**Comment by myahmao** [comment]
对，已经有了。不过那个是读书会的roadmap，单独网站的roadmap也可以。

**Comment by caogecym** [comment]
:+1: 如果还有什么正在使用的工具 let me know

**Comment by caogecym** [comment]
roadmap是整个组织的还是网站开发的？

**Comment by myahmao** [comment]
涛哥发的那个link是读书会的todo list，不只是网站的，网站只是其中的一部分

**Comment by caogecym** [comment]
那我们还是单独在来个todo吧，这样管理容易些

**Comment by myahmao** [comment]
可以啊
