### ISSUE TITLE
Create pages for LA(southern-california)

### ISSUE THREAD

**Issue by tao-guo** [valleyrain-org/www-old#7]
Create subpages for LA(southern-california), just like this:
http://asiasociety.org/southern-california

The front page is shared, but each site has its own pages.

**Comment by myahmao** [comment]
好复杂，等他们能弄起来再说。先加个tag，给他们发布信息就行了。

**Comment by myahmao** [comment]
搞一个完全一样的界面，他们谁去维护？

**Comment by tao-guo** [comment]
设计的时候要考虑这些扩展性
